DEFAULT:
  mineOriginalOnly: false
  usePermissions: false
  displayMessages:
    onBlockBreak: This %b will be available in %c seconds.
    onBlockProspect: This %b has already been mined.
  placeholder: 0
CONFIGURATION:
  w1_global:
    global: true
    volatile: true
    managedBlocks:
    - type: COAL_ORE
      cooldown: 30
      degrade: 0.5
    - type: IRON_ORE
      cooldown: 60
      degrade: 0.5
  w2_global:
    global: true
    managedBlocks:
    - type: GOLD_ORE
      cooldown: 120
      degrade: 0.5
    - type: DIAMOND_ORE
      cooldown: 240
      degrade: 0.5
  spawn:
    placeholder: BEDROCK
    managedBlocks:
    - type: COAL_ORE
      cooldown: 30
      degrade: 0
    mineOriginalOnly: true
  forest:
    placeholder: 18 3
    managedBlocks:
    - type: LOG 0
      cooldown: 30
      degrade: 0
    - type: LOG 1
      cooldown: 30
      degrade: 0
    - type: LOG 2
      cooldown: 30
      degrade: 0
    - type: 17 3
      cooldown: 30
      degrade: 0
    displayMessages:
      onBlockBreak: This tree is enchanted and will reappear in %c seconds.
      onBlockProspect: Magic is gathering in this area... be patient.
    mineOriginalOnly: true
  deadzone:
    active: false
