######### MineralManager 2.2 config

# The DEFAULT section sets the defaults for the application.
DEFAULT:
  # If true, only applies to blocks which were there, not placed.
  mineOriginalOnly: false

  # If true, you need the MineralManager.User permission for mining 
  # to cause respawn.
  usePermissions: false

  # Configurable messages.
  # Can be interpolated with special variables:
  #     %b = block name
  #     %c = cooldown, looks like '4m50s'
  #     %r = remaining cooldown, looks like '4m20s'
  displayMessages:
    onBlockBreak: This %b will be available in %c.
    onBlockProspect: This %b has already been mined.

  # What to use as the placeholder. Block ID 0 = AIR
  placeholder: AIR

# Here follows multiple configuration sections.
# Configuration sections are used to define different sets of managed
# blocks, and can be assigned to regions or even to entire worlds.
CONFIGURATION:
  # Section names are used in the command when adding regions.
  # Names must be unique and must only contain letters, numbers, and underscores.
  example_home:
    placeholder: WOOL 1


    # Set the managed blocks for this config.
    # Each managed block can have its own cooldown and 
    # degrade probability.
    managedBlocks:
    - type: COAL_ORE
      cooldown: 30   # 30 seconds
      degrade: 0.50  # 0.5 = 50%
    - type: IRON_ORE
      cooldown: 10m
      degrade: 0.05  # 0.05 = 5%
    - type: GLOWING_REDSTONE_ORE
      cooldown: 2h30m15s  # h = hour, m = minute, s = seconds
      degrade: 0.01  # 0.01 = 1%
    - type: DIAMOND_ORE
      cooldown: 30m
      degrade: 0.04
      placeholder: BEDROCK  # We can now set a placeholder per managed block.
    - type: GOLD_ORE
      cooldown: 45m
      degrade: 0.05
    - type: LAPIS_ORE
      cooldown: 45m
      degrade: 0.10
    - type: EMERALD_ORE
      cooldown: 1h45m
      degrade: 0.05

  # Dead zones are useful for having a location within a larger region
  # which does not have any ore respawning.
  deadzone:
    active: false

  # Sections can even override values from the DEFAULT section,
  # such as the placeholder and mineOriginalOnly configurations.
  example_override:
    placeholder: BEDROCK
    mineOriginalOnly: true

    displayMessages:
      # Custom blockBreak message has this region not telling you 
      # how long until the block is available again.
      onBlockBreak: This %b will be available at some point in the future.

    managedBlocks:
    - type: COAL_ORE
      cooldown: 30s
      degrade: 0

  #### Additional example sections.
  forest:
    placeholder: 18 3
    mineOriginalOnly: true

    # Volatile means that if the placeholder block is broken
    # then the block it's associated with will not respawn.
    volatile: true

    managedBlocks:
    - type: LOG 0
      cooldown: 30s
      degrade: 0
    - type: LOG 1
      cooldown: 30s
      degrade: 0
    - type: LOG 2
      cooldown: 45s
      degrade: 0
    - type: 17 3
      cooldown: 30s
      degrade: 0
    displayMessages:
      onBlockBreak: This tree is enchanted and will reappear in %c.
      onBlockProspect: Magic is gathering in this area... be patient.
